# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{family-jewels-test}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Wadsworth"]
  s.date = %q{2011-09-22}
  s.description = %q{A repository/gem for testing family jewels}
  s.email = %q{jdwadsworth@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "README",
    "Rakefile",
    "VERSION",
    "family-jewels-test.gemspec",
    "lib/fjt.rb"
  ]
  s.homepage = %q{http://github.com/subakva/family-jewels-test}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{A repo/gem for testing family jewels}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

